In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
mc = pd.read_csv("day_wise.csv", encoding="ISO-8859-1")

In [ ]:
mc.head()

Date  Confirmed  Deaths  Recovered  Active  New cases  New deaths  \
0  2020-01-22        555      17         28     510          0           0   
1  2020-01-23        654      18         30     606         99           1   
2  2020-01-24        941      26         36     879        287           8   
3  2020-01-25       1434      42         39    1353        493          16   
4  2020-01-26       2118      56         52    2010        684          14   

   New recovered  Deaths / 100 Cases  Recovered / 100 Cases  \
0              0                3.06                   5.05   
1              2                2.75                   4.59   
2              6                2.76                   3.83   
3              3                2.93                   2.72   
4             13                2.64                   2.46   

   Deaths / 100 Recovered  No. of countries  
0                   60.71                 6  
1                   60.00                 8  
2                   72.22                 9  
3                  107.69                11  
4                  107.69                13

In [ ]:
mc.pop('Date')

0      2020-01-22
1      2020-01-23
2      2020-01-24
3      2020-01-25
4      2020-01-26
          ...    
183    2020-07-23
184    2020-07-24
185    2020-07-25
186    2020-07-26
187    2020-07-27
Name: Date, Length: 188, dtype: object

In [ ]:
mc.head()

Confirmed  Deaths  Recovered  Active  New cases  New deaths  New recovered  \
0        555      17         28     510          0           0              0   
1        654      18         30     606         99           1              2   
2        941      26         36     879        287           8              6   
3       1434      42         39    1353        493          16              3   
4       2118      56         52    2010        684          14             13   

   Deaths / 100 Cases  Recovered / 100 Cases  Deaths / 100 Recovered  \
0                3.06                   5.05                   60.71   
1                2.75                   4.59                   60.00   
2                2.76                   3.83                   72.22   
3                2.93                   2.72                  107.69   
4                2.64                   2.46                  107.69   

   No. of countries  
0                 6  
1                 8  
2                 9  
3                11  
4                13

1.Finding Unique Values

In [ ]:
mc['No. of countries'].unique()

array([  6,   8,   9,  11,  13,  16,  18,  20,  24,  25,  26,  27,  28,
        30,  31,  36,  41,  47,  51,  57,  61,  66,  73,  76,  80,  84,
        93,  94,  99, 102, 105, 111, 113, 120, 133, 137, 143, 146, 150,
       154, 161, 163, 168, 169, 171, 174, 175, 176, 177, 179, 180, 182,
       183, 184, 186, 187])

2. Finding Null Values

In [ ]:
mc.isnull().sum()

Confirmed                 0
Deaths                    0
Recovered                 0
Active                    0
New cases                 0
New deaths                0
New recovered             0
Deaths / 100 Cases        0
Recovered / 100 Cases     0
Deaths / 100 Recovered    0
No. of countries          0
dtype: int64

4. Normalizing the data using standard scaler or minmax scaler

In [ ]:
from sklearn.preprocessing import StandardScaler
#importing sklearn library
scaler = StandardScaler()
#calling the function standardscaler
scaler.fit(mc.drop('Deaths', axis = 1))
#standardizing my class lable

StandardScaler()

In [ ]:
scaled_features = scaler.transform(mc.drop('Deaths', axis = 1))

In [ ]:
scaled_features

array([[-0.92857965, -0.78824523, -1.07394177, ..., -1.81240716,
         1.71517359, -2.12839909],
       [-0.92855879, -0.78824446, -1.0738929 , ..., -1.84086723,
         1.68362954, -2.097631  ],
       [-0.92849831, -0.78824217, -1.07375392, ..., -1.8878882 ,
         2.22654267, -2.08224695],
       ...,
       [ 2.45299301,  2.70614343,  2.10430126, ...,  1.40605484,
        -0.66929021,  0.65611318],
       [ 2.49611047,  2.75754447,  2.1377874 , ...,  1.41286051,
        -0.67195591,  0.65611318],
       [ 2.54430303,  2.82416961,  2.16255343, ...,  1.42956533,
        -0.67506588,  0.65611318]])

5. Apply KNN

In [ ]:
X = mc.iloc[:, [1, 2, 3]].values
y = mc.iloc[:, -1].values

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
y_test

array([186,  94, 187, 174, 187, 184,  26, 186, 187,  18,  16, 187, 187,
       180, 186, 184,  57, 184, 187, 182, 146, 187, 150, 184, 187, 187,
       187, 186, 187,  36,  13, 187, 187, 169,  93,  27, 187, 187])

In [ ]:
y_pred

array([186,  80, 187, 176, 187, 184,  26, 187, 187,  11,   8, 187, 187,
       179, 186, 184,  47, 184, 187, 183, 133, 187, 137, 184, 187, 187,
       187, 187, 187,  30,   6, 187, 187, 161,  76,  27, 187, 187])

6. Display the confusion matrix, accuracy measures, classification report.

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test,y_pred)

In [ ]:
confusion_matrix

<function sklearn.metrics._classification.confusion_matrix>

In [ ]:
cm

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  

In [ ]:
ac

0.6052631578947368

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))
#printing classifictaion report

              precision    recall  f1-score   support

           6       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         0
          11       0.00      0.00      0.00         0
          13       0.00      0.00      0.00         1
          16       0.00      0.00      0.00         1
          18       0.00      0.00      0.00         1
          26       1.00      1.00      1.00         1
          27       1.00      1.00      1.00         1
          30       0.00      0.00      0.00         0
          36       0.00      0.00      0.00         1
          47       0.00      0.00      0.00         0
          57       0.00      0.00      0.00         1
          76       0.00      0.00      0.00         0
          80       0.00      0.00      0.00         0
          93       0.00      0.00      0.00         1
          94       0.00      0.00      0.00         1
         133       0.00      0.00      0.00         0
         137       0.00    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1